spring.application.name=prontuario-api

spring.datasource.url=jdbc:postgresql://localhost:5432/prontuario_odonto
spring.datasource.username=prontuario_user
spring.datasource.password=prontuario_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080